#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Windows 8.1" {
	insmod part_msdos
		insmod ntfs
		set root="hd0,msdos1"
		chainloader +1
}
menuentry 'Gentoo Systemrescured altker32' {
	load_video
		insmod gzio
		insmod part_msdos
		insmod ext2
		set root='hd0,msdos3'
		echo	'Loading Linux altker32 ...'
		linux	/boot/altker32 root=/dev/sda3 ro single 
		echo	'Loading initial ramdisk ...'
		initrd	/boot/initram.igz
}
